#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy.sh — Full deploy (frontend + backend) to coderxp.app (87.106.111.220)
#
# Run from your LOCAL machine (not the server).
#
# What it does:
#   1.  Builds the React frontend with production env vars
#   2.  rsyncs the dist/ output to /var/www/coderxp/dist on the server
#   3.  rsyncs the server source to /opt/coderxp on the server
#   4.  On server: pnpm install (if package.json changed)
#   5.  On server: prisma migrate deploy
#   6.  On server: pm2 restart coderxp-server
#   7.  Verifies https://coderxp.app/health
#
# Usage:
#   chmod +x scripts/deploy.sh
#   ./scripts/deploy.sh
#
#   # Frontend only (skip backend rsync + restart):
#   DEPLOY_BACKEND=false ./scripts/deploy.sh
#
#   # Skip server restart (deploy code but keep old process running):
#   RESTART_SERVER=false ./scripts/deploy.sh
#
#   # Use a custom SSH key:
#   SSH_KEY=~/.ssh/my_key ./scripts/deploy.sh
#
# Prerequisites:
#   - SSH access to 87.106.111.220 (key-based auth recommended)
#   - rsync installed locally
#   - pnpm installed locally
#   - SSL already set up on the server (run setup-ssl.sh first)
#   - Server bootstrapped (run server-setup.sh on server first)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ─── Config ───────────────────────────────────────────────────

SERVER_IP="87.106.111.220"
SERVER_USER="${SERVER_USER:-root}"
SERVER_DEST="/var/www/coderxp/dist"
SERVER_APP_DIR="/opt/coderxp"
PM2_APP_NAME="coderxp-server"
SSH_KEY="${SSH_KEY:-}"
RESTART_SERVER="${RESTART_SERVER:-true}"
DEPLOY_BACKEND="${DEPLOY_BACKEND:-true}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB_DIR="$REPO_ROOT/apps/web"

# ─── Colour helpers ───────────────────────────────────────────

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
section() { echo -e "\n${GREEN}══════════════════════════════════════════${NC}"; echo -e "${GREEN}  $*${NC}"; echo -e "${GREEN}══════════════════════════════════════════${NC}"; }

# ─── SSH options ──────────────────────────────────────────────

SSH_OPTS="-o StrictHostKeyChecking=accept-new -o ConnectTimeout=15"
if [[ -n "$SSH_KEY" ]]; then
    SSH_OPTS="$SSH_OPTS -i $SSH_KEY"
fi

SSH_CMD="ssh $SSH_OPTS $SERVER_USER@$SERVER_IP"
RSYNC_SSH="ssh $SSH_OPTS"

# ─── Step 1: Write production .env for frontend build ─────────

section "Step 1: Prepare production environment"

PROD_ENV="$WEB_DIR/.env.production.local"

# Only write if it doesn't already exist (don't overwrite user customisations)
if [[ ! -f "$PROD_ENV" ]]; then
    info "Writing $PROD_ENV ..."
    cat > "$PROD_ENV" <<'ENV'
# Production environment — auto-generated by deploy.sh
# Edit this file to customise production build vars.
# This file is gitignored.

# When nginx proxies /api/* and /socket.io/* to localhost:3001,
# the frontend can use the same origin (empty string = relative URLs).
# Set to https://coderxp.app if you need absolute URLs.
VITE_API_URL=https://coderxp.app
VITE_SOCKET_URL=https://coderxp.app
ENV
    info "Created $PROD_ENV"
else
    info "Using existing $PROD_ENV"
fi

cat "$PROD_ENV"

# ─── Step 2: Build the frontend ───────────────────────────────

section "Step 2: Build frontend (Vite)"

cd "$REPO_ROOT"

info "Running pnpm install (frozen lockfile)..."
pnpm install --frozen-lockfile 2>&1 | tail -5

info "Building apps/web..."
cd "$WEB_DIR"
pnpm run build 2>&1

DIST_DIR="$WEB_DIR/dist"
[[ -d "$DIST_DIR" ]] || error "Build failed — dist/ not found at $DIST_DIR"

DIST_SIZE=$(du -sh "$DIST_DIR" | cut -f1)
FILE_COUNT=$(find "$DIST_DIR" -type f | wc -l)
info "Build complete: $DIST_SIZE, $FILE_COUNT files"

# ─── Step 3: Test SSH connection ──────────────────────────────

section "Step 3: Test SSH connection"

$SSH_CMD "echo 'SSH OK — hostname: \$(hostname)'" || error "SSH connection failed to $SERVER_USER@$SERVER_IP"

# ─── Step 4: Ensure target directory exists on server ─────────

section "Step 4: Prepare server directory"

$SSH_CMD "mkdir -p $SERVER_DEST && echo 'Directory ready: $SERVER_DEST'"

# ─── Step 5: rsync dist to server ─────────────────────────────

section "Step 5: Deploy dist to server"

info "Syncing $DIST_DIR → $SERVER_USER@$SERVER_IP:$SERVER_DEST ..."

rsync \
    --archive \
    --compress \
    --delete \
    --progress \
    --human-readable \
    -e "$RSYNC_SSH" \
    "$DIST_DIR/" \
    "$SERVER_USER@$SERVER_IP:$SERVER_DEST/"

info "rsync complete"

# ─── Step 6: Reload nginx (to pick up any new static files) ───

section "Step 6: Reload nginx"

$SSH_CMD "nginx -t && systemctl reload nginx && echo 'nginx reloaded'" || warn "nginx reload failed — check server logs"

# ─── Step 7: Deploy backend source ────────────────────────────

if [[ "$DEPLOY_BACKEND" == "true" ]]; then
    section "Step 7: Deploy backend source to server"

    info "Syncing source → $SERVER_USER@$SERVER_IP:$SERVER_APP_DIR ..."

    rsync \
        --archive \
        --compress \
        --delete \
        --progress \
        --human-readable \
        -e "$RSYNC_SSH" \
        --exclude 'node_modules' \
        --exclude '.git' \
        --exclude 'apps/web/dist' \
        --exclude 'apps/web/node_modules' \
        --exclude 'apps/server/node_modules' \
        --exclude 'apps/server/uploads' \
        --exclude 'apps/server/workspaces' \
        --exclude '*.log' \
        --exclude '.env.local' \
        --exclude '.env.production.local' \
        "$REPO_ROOT/" \
        "$SERVER_USER@$SERVER_IP:$SERVER_APP_DIR/"

    info "Backend source synced ✓"

    # Install dependencies on server (fast if lockfile unchanged)
    info "Running pnpm install on server..."
    $SSH_CMD "cd $SERVER_APP_DIR && pnpm install --frozen-lockfile 2>&1 | tail -5" \
        || warn "pnpm install had warnings — check server logs"

    # Run Prisma migrations
    info "Running Prisma migrations on server..."
    $SSH_CMD "
        cd $SERVER_APP_DIR/apps/server
        export \$(grep '^DATABASE_URL=' $SERVER_APP_DIR/.env.local | xargs)
        npx prisma migrate deploy && echo 'Migrations OK'
        npx prisma generate && echo 'Prisma client generated'
    " || warn "Prisma migration step had issues — check server logs"

    # Restart server
    if [[ "$RESTART_SERVER" == "true" ]]; then
        info "Restarting pm2 process: $PM2_APP_NAME ..."
        $SSH_CMD "
            if command -v pm2 &>/dev/null && pm2 list | grep -q '$PM2_APP_NAME'; then
                pm2 restart '$PM2_APP_NAME' && echo 'pm2: restarted $PM2_APP_NAME'
            elif command -v pm2 &>/dev/null; then
                cd $SERVER_APP_DIR/apps/server
                pm2 start npx \
                    --name '$PM2_APP_NAME' \
                    --cwd '$SERVER_APP_DIR/apps/server' \
                    --log '$SERVER_APP_DIR/apps/server/server.log' \
                    --error '$SERVER_APP_DIR/apps/server/server-err.log' \
                    --time \
                    -- tsx src/index.ts
                pm2 save
                echo 'pm2: started $PM2_APP_NAME (new process)'
            else
                echo 'WARN: pm2 not found — run server-setup.sh on the server first'
            fi
        " || warn "Server restart step failed — check server logs"
    else
        info "Skipping server restart (RESTART_SERVER=false)"
    fi
else
    info "Skipping backend deployment (DEPLOY_BACKEND=false)"
fi

# ─── Step 8: Verify deployment ────────────────────────────────

section "Step 8: Verify"

sleep 3

info "Checking https://coderxp.app/health ..."
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "https://coderxp.app/health" 2>/dev/null || echo "FAILED")

if [[ "$HTTP_STATUS" == "200" ]]; then
    info "✅ https://coderxp.app/health → $HTTP_STATUS"
else
    warn "⚠️  https://coderxp.app/health → $HTTP_STATUS"
fi

info "Checking https://coderxp.app/ (SPA) ..."
SPA_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "https://coderxp.app/" 2>/dev/null || echo "FAILED")
if [[ "$SPA_STATUS" == "200" ]]; then
    info "✅ https://coderxp.app/ → $SPA_STATUS"
else
    warn "⚠️  https://coderxp.app/ → $SPA_STATUS"
fi

# ─── Done ─────────────────────────────────────────────────────

section "Deploy Complete"

echo ""
echo -e "${GREEN}  ✅ CoderXP deployed to https://coderxp.app${NC}"
echo ""
echo "  Verify manually:"
echo "    curl https://coderxp.app/health"
echo "    curl https://coderxp.app/api/providers/status"
echo "    open https://coderxp.app"
echo ""
echo "  Server logs (run on server):"
echo "    pm2 logs $PM2_APP_NAME"
echo "    pm2 status"
echo ""
