/**
 * Scaffold Service — Legacy fallback (Phase 3B)
 *
 * NOTE: As of Phase 10, the primary code generator is codeGenerator.ts
 * (generateProjectFiles). This file is retained as a legacy fallback
 * and for direct use in tests / tooling.
 *
 * GENERATION MODE: Template-based (not AI-generated)
 * - Files are real, syntactically valid TypeScript/React
 * - Content is derived from plan data (summary, features, techStack)
 * - Uses premium dark-theme design system (designSystem.ts)
 *
 * Each file returned has actual content — no empty files, no placeholders.
 */

import {
  detectProjectType,
  getPremiumIndexCss,
  getPremiumTailwindConfig,
} from './designSystem'

// ─── Types ────────────────────────────────────────────────────

export interface ScaffoldFile {
  relativePath: string
  content: string
  description: string // What this file does
}

export interface ScaffoldInput {
  projectName: string
  summary: string
  features: string[]
  techStack: {
    frontend?: string[]
    backend?: string[]
    database?: string[]
    auth?: string[]
    integrations?: string[]
  }
  frontendScope: string[]
  backendScope: string[]
  integrations: string[]
}

export interface ScaffoldResult {
  files: ScaffoldFile[]
  generationMode: 'template'
  templateVersion: string
}

const TEMPLATE_VERSION = '3.0.0'

// ─── Helpers ──────────────────────────────────────────────────

function hasFeature(features: string[], ...keywords: string[]): boolean {
  const lower = features.map(f => f.toLowerCase())
  return keywords.some(k => lower.some(f => f.includes(k.toLowerCase())))
}

function hasIntegration(integrations: string[], ...keywords: string[]): boolean {
  const lower = integrations.map(i => i.toLowerCase())
  return keywords.some(k => lower.some(i => i.includes(k.toLowerCase())))
}

function hasBackend(backendScope: string[]): boolean {
  return backendScope.length > 0
}

function hasDatabase(techStack: ScaffoldInput['techStack']): boolean {
  return (techStack.database?.length ?? 0) > 0
}

// ─── File generators ──────────────────────────────────────────

function genPackageJson(input: ScaffoldInput): string {
  const hasAuth = hasFeature(input.features, 'auth', 'login', 'register', 'user')
  const hasStripe = hasIntegration(input.integrations, 'stripe', 'payment', 'billing')
  const hasDB = hasDatabase(input.techStack)
  const hasServer = hasBackend(input.backendScope)

  const deps: Record<string, string> = {
    'react': '^18.2.0',
    'react-dom': '^18.2.0',
    'react-router-dom': '^6.22.0',
    'axios': '^1.6.0',
  }

  if (hasServer) {
    deps['express'] = '^4.18.2'
    deps['cors'] = '^2.8.5'
    deps['dotenv'] = '^16.4.0'
    deps['helmet'] = '^7.1.0'
    deps['morgan'] = '^1.10.0'
  }

  if (hasAuth) {
    deps['jsonwebtoken'] = '^9.0.0'
    deps['bcryptjs'] = '^2.4.3'
  }

  if (hasDB) {
    deps['@prisma/client'] = '^5.22.0'
  }

  if (hasStripe) {
    deps['stripe'] = '^14.0.0'
  }

  const devDeps: Record<string, string> = {
    '@types/react': '^18.2.0',
    '@types/react-dom': '^18.2.0',
    '@vitejs/plugin-react': '^4.2.0',
    'typescript': '^5.3.0',
    'vite': '^5.1.0',
    'tailwindcss': '^3.4.0',
    'autoprefixer': '^10.4.0',
    'postcss': '^8.4.0',
  }

  if (hasServer) {
    devDeps['@types/express'] = '^4.17.21'
    devDeps['@types/cors'] = '^2.8.17'
    devDeps['tsx'] = '^4.7.0'
    devDeps['concurrently'] = '^8.2.0'
  }

  if (hasAuth) {
    devDeps['@types/jsonwebtoken'] = '^9.0.0'
    devDeps['@types/bcryptjs'] = '^2.4.6'
  }

  if (hasDB) {
    devDeps['prisma'] = '^5.22.0'
  }

  const scripts: Record<string, string> = {
    'dev': hasServer ? 'concurrently "vite" "tsx server/index.ts"' : 'vite',
    'build': 'tsc && vite build',
    'preview': 'vite preview',
  }

  if (hasServer) {
    scripts['server'] = 'tsx server/index.ts'
    scripts['start'] = 'node dist/server/index.js'
  }

  if (hasDB) {
    scripts['db:push'] = 'prisma db push'
    scripts['db:studio'] = 'prisma studio'
  }

  return JSON.stringify({
    name: input.projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    type: 'module',
    scripts,
    dependencies: deps,
    devDependencies: devDeps,
  }, null, 2)
}

function genReadme(input: ScaffoldInput): string {
  const featureList = input.features.map(f => `- ${f}`).join('\n')
  const techList = [
    ...(input.techStack.frontend ?? []),
    ...(input.techStack.backend ?? []),
    ...(input.techStack.database ?? []),
  ].join(', ')

  return `# ${input.projectName}

> ${input.summary}

## Features

${featureList}

## Tech Stack

${techList}

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Set up environment variables
cp .env.example .env

# Start development server
npm run dev
\`\`\`

## Project Structure

\`\`\`
src/           Frontend React application
server/        Backend Express API
prisma/        Database schema and migrations
public/        Static assets
\`\`\`

## Generated by CodedXP

This project was scaffolded by [CodedXP](https://codedxp.com) — the autonomous AI app builder.
`
}

function genGitignore(): string {
  return `# Dependencies
node_modules/
.pnp
.pnp.js

# Build output
dist/
build/
.next/
out/

# Environment variables
.env
.env.local
.env.*.local

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Prisma
prisma/migrations/

# TypeScript
*.tsbuildinfo
`
}

function genTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      useDefineForClassFields: true,
      lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      skipLibCheck: true,
      moduleResolution: 'bundler',
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
      strict: true,
      noUnusedLocals: false,
      noUnusedParameters: false,
      noFallthroughCasesInSwitch: true,
      baseUrl: '.',
      paths: {
        '@/*': ['./src/*'],
      },
    },
    include: ['src'],
    // Note: no tsconfig.node.json reference — vite.config.ts uses plain JS config
  }, null, 2)
}

function genTsConfigNode(): string {
  return JSON.stringify({
    compilerOptions: {
      composite: true,
      skipLibCheck: true,
      module: 'ESNext',
      moduleResolution: 'bundler',
      allowSyntheticDefaultImports: true,
      strict: true,
    },
    include: ['vite.config.ts'],
  }, null, 2)
}

function genViteConfig(input: ScaffoldInput): string {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 5173,
  },
})
`
}

function genIndexHtml(input: ScaffoldInput): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${input.projectName}</title>
    <meta name="description" content="${input.summary}" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

function genMainTsx(input: ScaffoldInput): string {
  return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`
}

function genAppTsx(input: ScaffoldInput): string {
  const hasAuth = hasFeature(input.features, 'auth', 'login', 'register', 'user')
  const hasDashboard = hasFeature(input.features, 'dashboard', 'admin', 'panel')

  const routes = [`        <Route path="/" element={<Home />} />`]
  const imports = [`import { Home } from './pages/Home'`]

  if (hasAuth) {
    routes.push(`        <Route path="/login" element={<Login />} />`)
    routes.push(`        <Route path="/register" element={<Register />} />`)
    imports.push(`import { Login } from './pages/Login'`)
    imports.push(`import { Register } from './pages/Register'`)
  }

  if (hasDashboard) {
    routes.push(`        <Route path="/dashboard" element={<Dashboard />} />`)
    imports.push(`import { Dashboard } from './pages/Dashboard'`)
  }

  return `import React from 'react'
import { HashRouter, Routes, Route } from 'react-router-dom'
import { Header } from './components/Header'
${imports.join('\n')}
import './index.css'

function App() {
  return (
    <HashRouter>
      <div className="min-h-screen bg-gray-50">
        <Header />
        <main>
          <Routes>
${routes.join('\n')}
          </Routes>
        </main>
      </div>
    </HashRouter>
  )
}

export default App
`
}

function genIndexCss(input: ScaffoldInput): string {
  const projectType = detectProjectType(input.frontendScope, input.summary, input.features)
  return getPremiumIndexCss(projectType)
}

function genHeaderComponent(input: ScaffoldInput): string {
  const hasAuth = hasFeature(input.features, 'auth', 'login', 'register', 'user')

  return `import React from 'react'
import { Link, useNavigate } from 'react-router-dom'

interface HeaderProps {
  isAuthenticated?: boolean
  onLogout?: () => void
}

export function Header({ isAuthenticated = false, onLogout }: HeaderProps) {
  const navigate = useNavigate()

  const handleLogout = () => {
    if (onLogout) onLogout()
    navigate('/')
  }

  return (
    <header className="bg-white shadow-sm border-b border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <Link to="/" className="text-xl font-bold text-gray-900">
              ${input.projectName}
            </Link>
          </div>
          <nav className="flex items-center gap-4">
            <Link to="/" className="text-gray-600 hover:text-gray-900 text-sm font-medium">
              Home
            </Link>
${hasAuth ? `            {isAuthenticated ? (
              <>
                <Link to="/dashboard" className="text-gray-600 hover:text-gray-900 text-sm font-medium">
                  Dashboard
                </Link>
                <button
                  onClick={handleLogout}
                  className="bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-md text-sm font-medium"
                >
                  Sign Out
                </button>
              </>
            ) : (
              <>
                <Link to="/login" className="text-gray-600 hover:text-gray-900 text-sm font-medium">
                  Sign In
                </Link>
                <Link
                  to="/register"
                  className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md text-sm font-medium"
                >
                  Get Started
                </Link>
              </>
            )}` : ''}
          </nav>
        </div>
      </div>
    </header>
  )
}
`
}

function genDashboardComponent(input: ScaffoldInput): string {
  const featureCards = input.features.slice(0, 6).map((feature, i) => `
        <div key="${i}" className="bg-white rounded-lg shadow p-6 border border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">${feature}</h3>
          <p className="text-gray-500 text-sm">Manage your ${feature.toLowerCase()} here.</p>
        </div>`).join('')

  return `import React from 'react'

export function Dashboard() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
        <p className="text-gray-500 mt-2">${input.summary}</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
${featureCards}
      </div>
    </div>
  )
}
`
}

function genHomePage(input: ScaffoldInput): string {
  const featureList = input.features.slice(0, 6).map(f =>
    `        <li className="flex items-center gap-2">
          <span className="text-green-500">✓</span>
          <span>${f}</span>
        </li>`
  ).join('\n')

  return `import React from 'react'
import { Link } from 'react-router-dom'

export function Home() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 text-center">
      <h1 className="text-5xl font-bold text-gray-900 mb-6">
        ${input.projectName}
      </h1>
      <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
        ${input.summary}
      </p>

      <div className="flex gap-4 justify-center mb-16">
        <Link
          to="/register"
          className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-lg text-lg font-semibold"
        >
          Get Started
        </Link>
        <Link
          to="/login"
          className="bg-white hover:bg-gray-50 text-gray-700 border border-gray-300 px-8 py-3 rounded-lg text-lg font-semibold"
        >
          Sign In
        </Link>
      </div>

      <div className="bg-white rounded-2xl shadow-lg p-8 text-left max-w-2xl mx-auto">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Features</h2>
        <ul className="space-y-3 text-gray-700">
${featureList}
        </ul>
      </div>
    </div>
  )
}
`
}

function genLoginPage(input: ScaffoldInput): string {
  return `import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import axios from 'axios'

export function Login() {
  const navigate = useNavigate()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      const res = await axios.post('/api/auth/login', { email, password })
      localStorage.setItem('token', res.data.token)
      navigate('/dashboard')
    } catch (err: any) {
      setError(err.response?.data?.error ?? 'Login failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Sign in to ${input.projectName}
          </h2>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
              {error}
            </div>
          )}
          <div className="space-y-4">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                Email address
              </label>
              <input
                id="email"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Password
              </label>
              <input
                id="password"
                type="password"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none disabled:opacity-50"
          >
            {loading ? 'Signing in...' : 'Sign in'}
          </button>
          <p className="text-center text-sm text-gray-600">
            Don't have an account?{' '}
            <Link to="/register" className="text-blue-600 hover:text-blue-500">
              Register
            </Link>
          </p>
        </form>
      </div>
    </div>
  )
}
`
}

function genRegisterPage(input: ScaffoldInput): string {
  return `import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import axios from 'axios'

export function Register() {
  const navigate = useNavigate()
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)
    try {
      const res = await axios.post('/api/auth/register', { name, email, password })
      localStorage.setItem('token', res.data.token)
      navigate('/dashboard')
    } catch (err: any) {
      setError(err.response?.data?.error ?? 'Registration failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            Create your account
          </h2>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleSubmit}>
          {error && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
              {error}
            </div>
          )}
          <div className="space-y-4">
            <div>
              <label htmlFor="name" className="block text-sm font-medium text-gray-700">
                Full name
              </label>
              <input
                id="name"
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                Email address
              </label>
              <input
                id="email"
                type="email"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
            <div>
              <label htmlFor="password" className="block text-sm font-medium text-gray-700">
                Password
              </label>
              <input
                id="password"
                type="password"
                required
                minLength={8}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              />
            </div>
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none disabled:opacity-50"
          >
            {loading ? 'Creating account...' : 'Create account'}
          </button>
          <p className="text-center text-sm text-gray-600">
            Already have an account?{' '}
            <Link to="/login" className="text-blue-600 hover:text-blue-500">
              Sign in
            </Link>
          </p>
        </form>
      </div>
    </div>
  )
}
`
}

function genApiClient(input: ScaffoldInput): string {
  return `import axios from 'axios'

const api = axios.create({
  baseURL: import.meta.env.VITE_API_URL ?? '',
  headers: { 'Content-Type': 'application/json' },
  timeout: 30_000,
})

// Attach auth token to every request
api.interceptors.request.use((config) => {
  const token = localStorage.getItem('token')
  if (token) {
    config.headers.Authorization = \`Bearer \${token}\`
  }
  return config
})

// Handle 401 globally
api.interceptors.response.use(
  (res) => res,
  (err) => {
    if (err.response?.status === 401) {
      localStorage.removeItem('token')
      window.location.href = '/login'
    }
    return Promise.reject(err)
  }
)

export default api
`
}

function genServerIndex(input: ScaffoldInput): string {
  const hasAuth = hasFeature(input.features, 'auth', 'login', 'register', 'user')

  return `import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import morgan from 'morgan'
import { apiRouter } from './routes/api'
${hasAuth ? "import { authRouter } from './routes/auth'" : ''}

const app = express()
const PORT = parseInt(process.env.PORT ?? '3001', 10)

// ─── Middleware ───────────────────────────────────────────────

app.use(helmet({ contentSecurityPolicy: false }))
app.use(cors({
  origin: process.env.CLIENT_URL ?? 'http://localhost:5173',
  credentials: true,
}))
app.use(morgan('dev'))
app.use(express.json({ limit: '10mb' }))
app.use(express.urlencoded({ extended: true }))

// ─── Routes ───────────────────────────────────────────────────

${hasAuth ? "app.use('/api/auth', authRouter)" : ''}
app.use('/api', apiRouter)

// Health check
app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() })
})

// 404 handler
app.use((_req, res) => {
  res.status(404).json({ error: 'Not found' })
})

// Error handler
app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error('[Error]', err.message)
  res.status(500).json({ error: err.message ?? 'Internal server error' })
})

// ─── Start ────────────────────────────────────────────────────

app.listen(PORT, () => {
  console.log(\`🚀 ${input.projectName} server running on http://localhost:\${PORT}\`)
})
`
}

function genApiRoutes(input: ScaffoldInput): string {
  const featureRoutes = input.features.slice(0, 4).map(f => {
    const name = f.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
    return `
// ─── ${f} ─────────────────────────────────────────────────────

router.get('/${name}', async (_req, res) => {
  try {
    // TODO: Implement ${f} listing
    res.json({ items: [], total: 0 })
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch ${f.toLowerCase()}' })
  }
})

router.post('/${name}', async (req, res) => {
  try {
    // TODO: Implement ${f} creation
    res.status(201).json({ id: 'new-id', ...req.body, createdAt: new Date() })
  } catch (err) {
    res.status(500).json({ error: 'Failed to create ${f.toLowerCase()}' })
  }
})`
  }).join('\n')

  return `import { Router } from 'express'

const router = Router()

// ─── Health ───────────────────────────────────────────────────

router.get('/status', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() })
})
${featureRoutes}

export { router as apiRouter }
`
}

function genAuthRoutes(input: ScaffoldInput): string {
  return `import { Router, Request, Response } from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'

const router = Router()
const JWT_SECRET = process.env.JWT_SECRET ?? 'dev-secret-change-in-production'

// ─── Register ─────────────────────────────────────────────────

router.post('/register', async (req: Request, res: Response): Promise<void> => {
  try {
    const { name, email, password } = req.body
    if (!name || !email || !password) {
      res.status(400).json({ error: 'Name, email, and password are required' })
      return
    }
    if (password.length < 8) {
      res.status(400).json({ error: 'Password must be at least 8 characters' })
      return
    }
    const hashedPassword = await bcrypt.hash(password, 12)
    // TODO: Save user to database
    const user = { id: 'user-id', name, email, createdAt: new Date() }
    const token = jwt.sign({ userId: user.id, email }, JWT_SECRET, { expiresIn: '7d' })
    res.status(201).json({ user, token })
  } catch (err) {
    res.status(500).json({ error: 'Registration failed' })
  }
})

// ─── Login ────────────────────────────────────────────────────

router.post('/login', async (req: Request, res: Response): Promise<void> => {
  try {
    const { email, password } = req.body
    if (!email || !password) {
      res.status(400).json({ error: 'Email and password are required' })
      return
    }
    // TODO: Look up user in database and verify password
    res.status(401).json({ error: 'Invalid email or password' })
  } catch (err) {
    res.status(500).json({ error: 'Login failed' })
  }
})

// ─── Me ───────────────────────────────────────────────────────

router.get('/me', async (req: Request, res: Response): Promise<void> => {
  try {
    const token = req.headers.authorization?.slice(7)
    if (!token) { res.status(401).json({ error: 'Unauthorized' }); return }
    const payload = jwt.verify(token, JWT_SECRET) as { userId: string; email: string }
    // TODO: Fetch user from database
    res.json({ user: { id: payload.userId, email: payload.email } })
  } catch {
    res.status(401).json({ error: 'Invalid token' })
  }
})

export { router as authRouter }
`
}

function genAuthMiddleware(): string {
  return `import { Request, Response, NextFunction } from 'express'
import jwt from 'jsonwebtoken'

export interface AuthRequest extends Request {
  userId?: string
}

const JWT_SECRET = process.env.JWT_SECRET ?? 'dev-secret-change-in-production'

export function requireAuth(req: AuthRequest, res: Response, next: NextFunction): void {
  try {
    const authHeader = req.headers.authorization
    if (!authHeader?.startsWith('Bearer ')) {
      res.status(401).json({ error: 'Missing or invalid authorization header' })
      return
    }
    const token = authHeader.slice(7)
    const payload = jwt.verify(token, JWT_SECRET) as { userId: string }
    req.userId = payload.userId
    next()
  } catch {
    res.status(401).json({ error: 'Invalid token' })
  }
}
`
}

function genPrismaSchema(input: ScaffoldInput): string {
  const hasAuth = hasFeature(input.features, 'auth', 'login', 'register', 'user')

  return `// ${input.projectName} — Prisma Schema
// Generated by CodedXP

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
${hasAuth ? `
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String
  password  String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("users")
}
` : ''}
// Add your models here
`
}

function genEnvExample(input: ScaffoldInput): string {
  const hasDB = hasDatabase(input.techStack)
  const hasStripe = hasIntegration(input.integrations, 'stripe', 'payment', 'billing')

  const lines = [
    '# Application',
    'NODE_ENV=development',
    'PORT=3001',
    'CLIENT_URL=http://localhost:5173',
    '',
    '# Auth',
    'JWT_SECRET=change-this-to-a-secure-random-string',
  ]

  if (hasDB) {
    lines.push('', '# Database', 'DATABASE_URL=postgresql://user:password@localhost:5432/mydb')
  }

  if (hasStripe) {
    lines.push('', '# Stripe', 'STRIPE_SECRET_KEY=sk_test_...', 'STRIPE_WEBHOOK_SECRET=whsec_...')
  }

  return lines.join('\n') + '\n'
}

function genTailwindConfig(input: ScaffoldInput): string {
  const projectType = detectProjectType(input.frontendScope, input.summary, input.features)
  return getPremiumTailwindConfig(projectType)
}

function genPostcssConfig(): string {
  return `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
}

// ─── Main scaffold generator ──────────────────────────────────

export function generateScaffold(input: ScaffoldInput): ScaffoldResult {
  const hasAuth = hasFeature(input.features, 'auth', 'login', 'register', 'user')
  const hasDB = hasDatabase(input.techStack)
  const hasServer = hasBackend(input.backendScope)

  const files: ScaffoldFile[] = []

  // ── Root config files ─────────────────────────────────────
  files.push({
    relativePath: 'package.json',
    content: genPackageJson(input),
    description: 'Project dependencies and scripts',
  })
  files.push({
    relativePath: 'README.md',
    content: genReadme(input),
    description: 'Project documentation',
  })
  files.push({
    relativePath: '.gitignore',
    content: genGitignore(),
    description: 'Git ignore rules',
  })
  files.push({
    relativePath: 'tsconfig.json',
    content: genTsConfig(),
    description: 'TypeScript compiler configuration',
  })
  files.push({
    relativePath: 'tsconfig.node.json',
    content: genTsConfigNode(),
    description: 'TypeScript config for Vite/Node tooling',
  })
  files.push({
    relativePath: 'vite.config.ts',
    content: genViteConfig(input),
    description: 'Vite bundler configuration',
  })
  files.push({
    relativePath: 'tailwind.config.js',
    content: genTailwindConfig(input),
    description: 'Premium Tailwind CSS configuration (dark theme)',
  })
  files.push({
    relativePath: 'postcss.config.js',
    content: genPostcssConfig(),
    description: 'PostCSS configuration',
  })
  files.push({
    relativePath: 'index.html',
    content: genIndexHtml(input),
    description: 'HTML entry point',
  })
  files.push({
    relativePath: '.env.example',
    content: genEnvExample(input),
    description: 'Environment variable template',
  })

  // ── Frontend source ───────────────────────────────────────
  files.push({
    relativePath: 'src/main.tsx',
    content: genMainTsx(input),
    description: 'React application entry point',
  })
  files.push({
    relativePath: 'src/App.tsx',
    content: genAppTsx(input),
    description: 'Root App component with routing',
  })
  files.push({
    relativePath: 'src/index.css',
    content: genIndexCss(input),
    description: 'Global CSS with premium dark-theme design system',
  })
  files.push({
    relativePath: 'src/lib/api.ts',
    content: genApiClient(input),
    description: 'Axios API client with auth interceptors',
  })

  // ── Components ────────────────────────────────────────────
  files.push({
    relativePath: 'src/components/Header.tsx',
    content: genHeaderComponent(input),
    description: 'Navigation header component',
  })
  files.push({
    relativePath: 'src/components/Dashboard.tsx',
    content: genDashboardComponent(input),
    description: 'Dashboard overview component',
  })

  // ── Pages ─────────────────────────────────────────────────
  files.push({
    relativePath: 'src/pages/Home.tsx',
    content: genHomePage(input),
    description: 'Landing / home page',
  })

  if (hasAuth) {
    files.push({
      relativePath: 'src/pages/Login.tsx',
      content: genLoginPage(input),
      description: 'Login page with form validation',
    })
    files.push({
      relativePath: 'src/pages/Register.tsx',
      content: genRegisterPage(input),
      description: 'Registration page with form validation',
    })
  }

  // ── Backend ───────────────────────────────────────────────
  if (hasServer) {
    files.push({
      relativePath: 'server/index.ts',
      content: genServerIndex(input),
      description: 'Express server entry point',
    })
    files.push({
      relativePath: 'server/routes/api.ts',
      content: genApiRoutes(input),
      description: 'Feature API routes',
    })

    if (hasAuth) {
      files.push({
        relativePath: 'server/routes/auth.ts',
        content: genAuthRoutes(input),
        description: 'Authentication routes (register, login, me)',
      })
      files.push({
        relativePath: 'server/middleware/auth.ts',
        content: genAuthMiddleware(),
        description: 'JWT authentication middleware',
      })
    }
  }

  // ── Database ──────────────────────────────────────────────
  if (hasDB) {
    files.push({
      relativePath: 'prisma/schema.prisma',
      content: genPrismaSchema(input),
      description: 'Prisma database schema',
    })
  }

  return {
    files,
    generationMode: 'template',
    templateVersion: TEMPLATE_VERSION,
  }
}
